anongid: 1000
anonuid: 1000
export_path: /export/pool0/homes
link_dirname: /data
link_basename: homes
mount_path: /mnt/homes
mount_options: soft,timeo=100,nosuid
nfs_client_subnet: 10.240.0.0/16
nfs_server_ip: 10.240.0.14
zfs_dataset: pool0/homes
